VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsArray"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public vArrayRaw As String
Public vSelected As Boolean
Public vCode As String
Public vLandfill As String
Public vUTVR As String
Public vTotal As Double
Public vTrash As Double
Public vTechnology As Double
Public vInbound As Double
Public vOutbound As Double
Public vSubArray As Collection

