VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsCity"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public vCityName As String
Public vIBGECode As Double
Public vUF As String
Public vUFCode
Public vLatitude As Double
Public vLongitude As Double
Public vPopulation As Double
Public vTrash As Double
Public vConventionalCost As Double
Public vTransshipmentCost As Double
Public vCostPostTransshipment As Double
Public vUTVR As Boolean
Public vExistentLandfill As Boolean
Public vPotentialLandfill As Boolean


